### ISSUE TITLE
ratelimit and interations

### ISSUE THREAD

**Issue by NadineSahin** [abjer/sds#22]
We are having a problem with the following code.
First we specified our url, and now we are trying to put iterations=10 and a ratelimit. Does anyone has a clue of, why it is not working?

import time

def ratelimit():
    time.sleep(1) # sleep one second.

def get(url, iterations=10,check_function=lambda x: x.ok):
    
    for iteration in range(iterations):
        try:
            ratelimit(10) 
            response = session.get(url)
            if check_function(response):
                return response
        except exceptions as e: 
            print(e) 
    return None

**Comment by snorreralund** [comment]
What is the error message? 

The function assummes that you are using a session object, instead of requests.get. So either change the line: `response = session,get()`, og define a `session` using requests first:
`session = requests.session()`

The session object will allow you to set your standard parameters, like what information you will send to the server. This could be imitating a certain browser or for being more transparent by sending your mail and name to the webmaster.

**Comment by abjer** [comment]
@NadineSahin is this problem solved?
