### ISSUE TITLE
Splitting time series data for CV?

### ISSUE THREAD

**Issue by ghost** [abjer/sds#24]
What split to use?

**Comment by abjer** [comment]
I recommend using the built-in use of time series split method for sklearn, i.e. `TimeSeriesSplit`, in `sklearn.model_selection` as suggested by #25. This built-in method requires that we only use past and present data to predict the future. 

Note that an alternative is to use block sampling as described [here](https://stats.stackexchange.com/questions/25706/how-do-you-do-bootstrapping-with-time-series-data) which works by cutting of the dependency across models in order to make them stationary.
